goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../cljs_intro/g2d.js", ['cljs_intro.g2d'], ['cljs.core']);
goog.addDependency("../cljs_intro/core.js", ['cljs_intro.core'], ['cljs.core', 'clojure.string', 'cljs_intro.g2d']);
goog.addDependency("../cljs_intro/draw.js", ['cljs_intro.draw'], ['cljs.core', 'cljs_intro.core', 'cljs_intro.g2d']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core', 'cljs.core.async.impl.buffers', 'goog.async.nextTick']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols']);
goog.addDependency("../dommy/utils.js", ['dommy.utils'], ['cljs.core']);
goog.addDependency("../dommy/core.js", ['dommy.core'], ['cljs.core', 'dommy.utils', 'clojure.string']);
goog.addDependency("../cljs_intro/spot.js", ['cljs_intro.spot'], ['cljs.core', 'cljs_intro.core', 'cljs_intro.g2d']);
goog.addDependency("../cljs_intro/data.js", ['cljs_intro.data'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core', 'cljs.core.async.impl.buffers', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.timers']);
goog.addDependency("../cljs_intro/global.js", ['cljs_intro.global'], ['cljs.core', 'cljs_intro.core', 'cljs_intro.g2d']);
goog.addDependency("../cljs_intro/web.js", ['cljs_intro.web'], ['cljs_intro.data', 'cljs.core', 'cljs.core.async', 'cljs_intro.global', 'cljs_intro.core', 'cljs_intro.spot', 'cljs_intro.draw', 'dommy.core', 'cljs_intro.g2d']);
